{% set name = "cudaDecon" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scopetools/cudaDecon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5aed121463495eec9d62c159cdf94106a2674c9051c397a934551fb9960cca27

build:
  number: 2
  skip: True  # [osx or (cuda_compiler_version in ('None', 'undefined'))]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make  # [not win]
    - libgomp  # [linux]
  host:
    - boost-cpp
    - libtiff
    - fftw
  run:
    - boost-cpp

test:
  imports:
  commands:
    - cudaDecon --help

about:
  home: https://github.com/scopetools/cudaDecon
  license: LicenseRef-Janelia-Open-Source
  license_family: OTHER
  license_file: LICENSE
  summary: 'GPU accelerated 3D image deconvolution using CUDA'
  description: |
    GPU accelerated 3D image deconvolution using CUDA.
    Developed in the Betzig lab at Janelia by Lin Shao and Dan Milkie.
  doc_url: https://github.com/scopetools/cudaDecon#readme
  dev_url: https://github.com/scopetools/cudaDecon

extra:
  recipe-maintainers:
    - tlambert03
    - zbarry
    - dmilkie
